apiVersion: v1
kind: Service
metadata:
  name: profile-app-service
spec:
  selector:
    app: profile-app
  ports:
    - protocol: TCP
      port: 6544  # Port on which the service listens
      targetPort: 6544  # Port on the pods to forward traffic to
  type: LoadBalancer  # Expose the service externally via LoadBalancer
