apiVersion: v1
kind: Pod
metadata:
  name: docker-image-build
spec:
    containers:
        - name: ez-docker-helm-build
          image: ezezeasy/ez-docker-helm-build:1.41
          command: ["tail", "-f", "/dev/null"]
          imagePullPolicy: Always
          volumeMounts:
            - name: docker
              mountPath: /var/run/docker.sock
    volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock

